import bus from './bus'
import { getDefs, setAgentState, initDefs } from './agents'
import { abortAll } from './orchestrator'
import { runFinalGate } from './gates'
import { emitPolicyApplied } from './policies'

export type Speed = 1 | 2 | 4

let speed: Speed = 1
let active = false
let timers: ReturnType<typeof setTimeout>[] = []

export function setSpeed(s: Speed) {
  speed = s
}

export function getSpeed(): Speed {
  return speed
}

export function runSimulation(objective: string) {
  reset()
  active = true
  initDefs()
  bus.emit({ type: 'mission-start', objective })

  const defs = getDefs()
  const orchestrator = defs[0]
  const workers = defs.slice(1)

  const t = (ms: number) => ms / speed

  timers.push(
    setTimeout(() => {
      if (!active) return
      bus.emit({ type: 'plan-step', n: 1, total: 3, thought: 'Analyze objective and spawn scouts.' })
      const scoutIds = workers.slice(0, 2).map((d) => d.id)
      for (const id of scoutIds) {
        setAgentState(id, 'running')
        bus.emit({ type: 'agent-start', agent: id })
        bus.emit({ type: 'dispatch', from: orchestrator.id, to: id, tag: 'SCOUT' })
      }
      emitTokens(scoutIds[0], t(400))
      emitTokens(scoutIds[1], t(600))
    }, t(400))
  )

  timers.push(
    setTimeout(() => {
      if (!active) return
      bus.emit({ type: 'plan-step', n: 2, total: 3, thought: 'Converge findings from scouts.' })
      const analyzer = workers[2]
      setAgentState(analyzer.id, 'running')
      bus.emit({ type: 'agent-start', agent: analyzer.id })
      bus.emit({ type: 'dispatch', from: orchestrator.id, to: analyzer.id, tag: 'CONVERGE' })
      emitTokens(analyzer.id, t(700))
    }, t(1200))
  )

  timers.push(
    setTimeout(() => {
      if (!active) return
      bus.emit({ type: 'plan-step', n: 3, total: 3, thought: 'Compose final artifact.' })
      const writer = workers[3]
      setAgentState(writer.id, 'running')
      bus.emit({ type: 'agent-start', agent: writer.id })
      bus.emit({ type: 'dispatch', from: orchestrator.id, to: writer.id, tag: 'ARTIFACT' })
      emitTokens(writer.id, t(800))
    }, t(2200))
  )

  timers.push(
    setTimeout(() => {
      if (!active) return
      const writer = workers[3]
      for (const w of workers) setAgentState(w.id, 'done')
      const final = `# Mission Complete\n\nObjective: ${objective}\n\nSimulated artifact generated by AXIOM.\n\n## Summary\n\nAll dispatched agents converged and produced the requested artifact.\n\n## Key Points\n\n- Agents executed in parallel as planned.\n- Tokens streamed to the event feed in real time.\n- Mission persisted to local history.`
      bus.emit({ type: 'artifact-stored', id: 'sim-artifact-1', agent: writer.id, kind: 'final', summary: 'Simulated final artifact' })
      runFinalGate({ id: 'sim-artifact-1', nodeId: writer.id, kind: 'final', summary: 'Simulated final artifact', content: final }).then((gate) => {
        bus.emit({ type: 'mission-complete', final, artifactId: 'sim-artifact-1', verified: gate.verdict === 'pass' })
      })
      emitPolicyApplied('RESEARCHER', 'skip', 'simulated policy skip')
      bus.emit({ type: 'convergence', reason: 'dry-rounds', rounds: 2 })
      active = false
    }, t(3200))
  )
}

function emitTokens(agent: string, duration: number) {
  const parts = ['Analyzing ', 'data ', 'streams ', '... ', 'converging ', 'results ', 'done.']
  const step = duration / parts.length
  for (let i = 0; i < parts.length; i++) {
    const tid = setTimeout(() => {
      if (!active) return
      bus.emit({ type: 'token', agent, text: parts[i] })
    }, step * i)
    timers.push(tid)
  }
  const done = setTimeout(() => {
    if (!active) return
    setAgentState(agent, 'done')
    bus.emit({ type: 'agent-done', agent })
  }, duration)
  timers.push(done)
}

export function reset() {
  active = false
  for (const t of timers) clearTimeout(t)
  timers = []
  abortAll()
  initDefs()
}
